<?php

return [
    'provider' => env('CHAT_PROVIDER', config('enrichment.provider', 'openai')),
    'model' => env('CHAT_MODEL', config('enrichment.model', 'gpt-4o-mini')),
    'max_sources' => 12,
    'link_limit' => 6,
    'max_chars_per_page' => 12000,
    'retrieval_chunk_limit' => 8,
    'retrieval_neighbor_window' => (int) env('CHAT_RETRIEVAL_NEIGHBOR_WINDOW', 1),
    'retrieval_max_evidence' => (int) env('CHAT_RETRIEVAL_MAX_EVIDENCE', 24),
    'retrieval_fts_limit' => 6,
    'vector_enabled' => (bool) env('CHAT_VECTOR_ENABLED', true),
    'fts_enabled' => (bool) env('CHAT_FTS_ENABLED', true),
    'embedding_provider' => env('CHAT_EMBEDDING_PROVIDER', 'openai'),
    'embedding_model' => env('CHAT_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'embedding_dimensions' => (int) env('CHAT_EMBEDDING_DIMENSIONS', 1536),
    'embedding_api_key' => env('CHAT_EMBEDDING_API_KEY', env('OPENAI_API_KEY')),
    'embedding_base_url' => env('CHAT_EMBEDDING_BASE_URL', 'https://api.openai.com/v1'),
    'embedding_timeout' => (int) env('CHAT_EMBEDDING_TIMEOUT', 30),
    'embedding_retries' => (int) env('CHAT_EMBEDDING_RETRIES', 2),
    'chunk_max_chars' => (int) env('CHAT_CHUNK_MAX_CHARS', 1200),
    'chunk_overlap_chars' => (int) env('CHAT_CHUNK_OVERLAP_CHARS', 200),
    'chunk_min_chars' => (int) env('CHAT_CHUNK_MIN_CHARS', 200),
    'crawl_max_pages' => (int) env('CHAT_CRAWL_MAX_PAGES', 250),
    'crawl_max_depth' => (int) env('CHAT_CRAWL_MAX_DEPTH', 3),
    'crawl_allow_external' => (bool) env('CHAT_CRAWL_ALLOW_EXTERNAL', false),
    'crawl_max_chars_per_page' => (int) env('CHAT_CRAWL_MAX_CHARS_PER_PAGE', 0),
    'crawl_queue' => env('CHAT_CRAWL_QUEUE', 'ingestion'),
    'embedding_queue' => env('CHAT_EMBEDDING_QUEUE', 'embedding'),
    'crawl_job_timeout' => (int) env('CHAT_CRAWL_JOB_TIMEOUT', 1200),
    'crawl_renderer' => env('CHAT_CRAWL_RENDERER', 'auto'),
    'crawl_min_text_chars' => (int) env('CHAT_CRAWL_MIN_TEXT_CHARS', 800),
    'playwright_timeout' => (int) env('CHAT_PLAYWRIGHT_TIMEOUT', 30000),
    'playwright_wait_selector' => env('CHAT_PLAYWRIGHT_WAIT_SELECTOR'),
    'playwright_min_html_chars' => (int) env('CHAT_PLAYWRIGHT_MIN_HTML_CHARS', 20000),
    'playwright_script' => env('CHAT_PLAYWRIGHT_SCRIPT', base_path('scripts/chat/fetch-page.mjs')),
    'min_evidence_score_per_page' => 1,
    'min_evidence_score_total' => 2,
    'min_evidence_count' => 1,
    'cache_ttl' => (int) env('CHAT_CACHE_TTL', 1800),
    'http_timeout' => (int) env('CHAT_HTTP_TIMEOUT', 20),
    'http_retries' => (int) env('CHAT_HTTP_RETRIES', 2),
    'fetch_timeout' => (int) env('CHAT_FETCH_TIMEOUT', 12),
    'fetch_retries' => (int) env('CHAT_FETCH_RETRIES', 1),
    'user_agent' => env('CHAT_USER_AGENT', 'LocalmanacBot/1.0'),
    'rate_limit_per_minute' => 30,
];
